### PR TITLE
Fix ProfileReadyCard visibility

### LINKED ISSUE #495: Your Profile Is Ready shows after starting a chat
Your Profile is Ready occasionally shows after you have started or being invited to a chat, or you have dismissed the callout. This should not be the case. As soon as you accept a chat, start a chat, or dismiss the callout it should not show anymore.

### PR DESCRIPTION
**Pull request by untreu2**
## Description
Added automatic dismissal logic to hide the ProfileReadyCard when users perform any of the key actions the card encourages:

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

## Checklist

- [x] Run `just precommit` to ensure that formatting and linting are correct
- [x] Run `just check-flutter-coverage` to ensure that flutter coverage rules are passing
- [ ] Updated the `CHANGELOG.md` file with your changes (if they affect the user experience)

Fixes #495 

## Summary by CodeRabbit

* **Bug Fixes**
  * Profile Ready card now automatically dismisses after accepting the welcome prompt.
  * Profile Ready card now dismisses when starting a new direct message from the contact list.
  * Profile Ready card now auto-hides when the user has existing groups, avoiding redundant display.

* **Refactor**
  * Streamlined UI flow to prevent lingering cards during navigation, improving clarity and reducing visual clutter across contact-list interactions.

### CODE REVIEW

File: lib/ui/contact_list/widgets/profile_ready_card.dart [hunk 1]
```diff
@@ -93,7 +93,11 @@ class ProfileReadyCard extends ConsumerWidget {
           // Search For Friends button
           WnFilledButton(
             label: 'Search For Friends',
-            onPressed: () => NewChatBottomSheet.show(context),
+            onPressed: () {
+              // Dismiss the card when user takes action to search for friends
+              ref.read(profileReadyCardVisibilityProvider.notifier).dismissCard();
```
Comment (josefinalliende) [inline lib/ui/contact_list/widgets/profile_ready_card.dart:98]: But, if it doesn't start a chat, just searches, then I understand that we do want to show it right? Or not?

**Review by josefinalliende — CHANGES_REQUESTED** [review]
I don't think this fixes the issue liked to the PR, I tried it locally and could replicate the case and when changing to this branch it still happens. 
Screenshot 2025-08-31 at 11 07 31 PM
ens to me:;

**Comment by untreu2** [comment]
@josefinalliende Can you try resetting your simulator?

File: lib/ui/contact_list/start_chat_bottom_sheet.dart [hunk 2]
```diff
@@ -134,6 +135,9 @@ class _StartChatBottomSheetState extends ConsumerState<StartChatBottomSheet> {
         _logger.info('Direct message group created successfully: ${group.mlsGroupId}');
 
         if (mounted) {
+          // Dismiss the ProfileReadyCard since user has successfully started a chat
+          ref.read(profileReadyCardVisibilityProvider.notifier).dismissCard();
+
```
[the remark this answers is not in the document]
Comment (Quwaysim) [reply lib/ui/contact_list/start_chat_bottom_sheet.dart:140]: What @coderabbitai said.

File: lib/ui/contact_list/widgets/profile_ready_card.dart (hunk 1 above)
Comment (josefinalliende) [reply lib/ui/contact_list/widgets/profile_ready_card.dart:98]: @vladimir-krstic  WDYT?

Comment (josefinalliende) [reply lib/ui/contact_list/widgets/profile_ready_card.dart:98]: @untreu2  so maybe the change could be: first check if the card is visible and there are any groups. If so, call dismissCard(), instead of triggering it on the “start chat” button click.

**Review by Quwaysim — APPROVED** [review]
LGTM
