### PR TITLE
Fix chat header delay

### LINKED ISSUE #741: Chat header appears with delay
https://github.com/user-attachments/assets/f9f5ca93-447d-40c9-b551-993efe4429a2

When I scroll down and then quickly scroll back up, I notice a slight delay in the chat header, which includes the prominent image and the chat name. I’m not sure why this happens. It’s likely because the system is attempting to load Metadata in the background and only displays it once the metadata is ready. We should explore alternative methods to ensure that the chat header is always loaded on the page and remains cached, preventing unnecessary reloads.

### PR DESCRIPTION
**Pull request by untreu2**
## Description
Problem:
- Chat header (user name, profile image) shows loading delay when entering chat
- FutureBuilder was making API calls on every render
- Users see "loading..." state before header appears
- No caching mechanism for DMChatData

Solution:
- Added DMChatData caching to ChatState with dmChatDataCache field
- Integrated caching into ChatNotifier with getDMChatData(), preloadDMChatData() methods
- Replaced FutureBuilder with Consumer for instant data access from cache
- Added preloading to load data before user sees it

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

## Checklist

- [x] Run `just precommit` to ensure that formatting and linting are correct
- [ ] Run `just check-flutter-coverage` to ensure that flutter coverage rules are passing
- [ ] Updated the `CHANGELOG.md` file with your changes (if they affect the user experience)

Fixes #741

## Summary by CodeRabbit

* **Performance Improvements**
  * Intelligent per-conversation caching and preloading for direct messages to speed up loading and reduce repeat network requests

* **UI/UX Enhancements**
  * Improved loading states for direct-message headers and app bar titles when DM data is pending
  * Removed technical NPUB text from group headers for a cleaner chat view

### CODE REVIEW

File: lib/config/providers/chat_provider.dart [hunk 1]
```diff
@@ -745,6 +752,118 @@ class ChatNotifier extends Notifier<ChatState> {
...
+  Future<DMChatData?> _loadDMChatData(String groupId) async {
+    const maxRetries = 2;
+    int attempt = 0;
+
+    while (attempt <= maxRetries) {
+      try {
+        final otherMember = ref.read(groupsProvider.notifier).getOtherGroupMember(groupId);
+
+        if (otherMember != null) {
+          final user = await wn_users_api.getUser(pubkey: otherMember.publicKey);
```
Comment (josefinalliende) [inline lib/config/providers/chat_provider.dart]: Why not using user profile provider? it looks like the `getUserProfile ` does the same but it is tested (alles the get user method, then transforms the response to a UserProfile object

**Review by josefinalliende — COMMENTED** [review]
Tried it locally and it feels a lot faster 🏃🏻‍♂️  Left a comment related to logic that I think it's duplicated and already available in the userProfile provider

**Review by codeswot — APPROVED** [review]
