### PR TITLE
Fix in chat search results icon color

### LINKED ISSUE #485: In chat Search results icon color fix
In chat Search chevron icon color for cycling between results is broken in dark mode. In both Light and Dark mode chevron icons should use Primary Solid color variable.

Dark mode In app(broken):
Image

Figma Design(good):
https://www.figma.com/design/dGJqv6m6pchdcwxJEwxxzB/White-Noise---Design-System?node-id=1483-36230&t=2qKwCTh4ERDd7Q83-1

### PR DESCRIPTION
**Pull request by untreu2**
## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

## Checklist

- [x] Run `just precommit` to ensure that formatting and linting are correct
- [x] Run `just check-flutter-coverage` to ensure that flutter coverage rules are passing
- [ ] Updated the `CHANGELOG.md` file with your changes (if they affect the user experience)

Fixes #485 

## Summary by CodeRabbit

* **Style**
  * Harmonized theme colors across the app: updated chevron icons and various headings to use the current primary color token for consistent visuals.
  * Minor UI polish only; no changes to behavior, functionality, or settings.

### CODE REVIEW

File: lib/ui/chat/widgets/chat_search_widget.dart [hunk 1]
```diff
@@ -139,7 +139,7 @@ class _ChatSearchWidgetState extends ConsumerState<ChatSearchWidget> {
                       height: 16.w,
                       width: 16.w,
                       colorFilter: ColorFilter.mode(
-                        context.colors.primarySolid,
+                        context.colors.solidPrimary,
```
Comment (Quwaysim) [inline lib/ui/chat/widgets/chat_search_widget.dart:142]: Just checked, solidPrimary and primarySolid are both the same value in their light and dark modes. If this is intended as a cleanup, please remove one of them from the appTheme, probably primarySolid (and please help correct all the instances). Thanks.

**Review by Quwaysim — CHANGES_REQUESTED** [review]

File: lib/ui/chat/widgets/chat_search_widget.dart (hunk 1 above)
Comment (josefinalliende) [reply lib/ui/chat/widgets/chat_search_widget.dart:142]: Good catch!

**Review by Quwaysim — APPROVED** [review]
LGTM
