### PR TITLE
Fix chat UI bugs and message draft logic

### LINKED ISSUE #592: Erase drafts only of account that has been logged out
# Context  
In [#566](#566), draft messages were implemented — and they work great! 🎉  

Currently, when **any account logs out**, *all* drafts are deleted.  
This was intentional for now, since handling it properly wasn’t a priority in the first version.  

We’re creating this issue as a reminder that this is not a bug 😅  

# Solution  
The ideal behavior would be that **only the drafts of the account that logs out are deleted**, not all drafts.

### LINKED ISSUE #647: Chat bubbles width not hugging content properly
In some instances chat bubbles still don't hug content properly. Examples below:

Image
Image

### LINKED ISSUE #753: (Member > Send Message) Chat scroll position is wrong
When I go to a chat from the chat list, it scrolls to the bottom, when I go to a chat from Member > Send Message, I see the top of the chat.
https://github.com/user-attachments/assets/5c8bc4ac-c021-485f-b139-3e2b293050aa

### PR DESCRIPTION
**Pull request by untreu2**
## Description
This PR fixes various bugs about message drafts, chat screen and message widget.

- Drafts were broken, probably due to some provider changes. This issue is now fixed, and drafts are now being cleaned up on account basis. This fixes #592.

- There were some scenarios not considered for the message widget alignment, which caused hugging issues, and this (#647) has been fixed.

-  If you went to a DM from the group info screen, the scroll position wasn't set correctly, this bug has been fixed. Now, when you go to a chat using the ‘Send message’ button on the group info screen, the chat screen opens scrolled to the bottom of the screen. This fixes #753.

Screenshot 2025-11-03 at 01 00 27

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

## Checklist

- [x] Run `just precommit` to ensure that formatting and linting are correct
- [ ] Run `just check-flutter-coverage` to ensure that flutter coverage rules are passing
- [ ] Updated the `CHANGELOG.md` file with your changes (if they affect the user experience)

Fixes #592 
Fixes #647 
Fixes #753 

## Summary by CodeRabbit

* **New Features**
  * Drafts are now scoped to the active account; drafts can be saved, loaded, cleared per account and all drafts for an account can be removed.

* **Bug Fixes**
  * Improved initial auto-scroll behavior and last-read saving.
  * More consistent timestamp and message layout when media are present.
  * Chat input preserves and restores drafts correctly when switching accounts.

* **Tests**
  * Added tests verifying per-account draft isolation and related behaviors.

* **Chores**
  * Logout now clears drafts only for the active account and adds logging around draft clearance.

### CODE REVIEW

**Review by josefinalliende — COMMENTED** [review]
Scroll fix from the group info to DM works perfect 👍🏻 . Left some comments about drafts and hugging ( I tried it in my iPhone in commit 0585da3da0aa10c9a7d96f7a40d1faed46ce322c )

1) If I have two accounts in same group (DM in this case) and write a draft with one and then switch accounts, the draft of the other account is kept in the group.

https://github.com/user-attachments/assets/b670c0e2-e405-4359-a3d3-d07c1f284803

Maybe this one is a separate issue? But was surpised cause now the draft key includes the author pubkey so it was weird that this happens with that change... 

2) If I have 2 accounts in my phone with a DM, write a draft in one, switch acconunts and logout, the draft dissapears for the account that wrote it in the same place... so it seems to me that #592 is not fixed. 
Here a recording of what happened to me


https://github.com/user-attachments/assets/5cfed52c-d14f-4ba9-becb-28b90743db6b

3) Message hugging improved in comparison to the picture 🎉  For the user who receives it looks good, but I feel is still weird that for the sender the text still  looks in the left side of the bubble instead of more to the right... 
hugging

**Review by codeswot — DISMISSED** [review]

**Review by Quwaysim — CHANGES_REQUESTED** [review]
Just some fixes to go

**Comment by untreu2** [comment]
@josefinalliende Yes, you're right about drafts. But hugging is currently working as ‘planned’. So it's a choice.

**Review by josefinalliende — APPROVED** [review]
✅  Tried in my iPhone and drafts work perfect now. Both issues are fixed. Related to hugging, if that's the design choice, I'm ok.

File: lib/ui/chat/widgets/chat_input.dart [hunk 1]
```diff
@@ -40,7 +41,11 @@ class _ChatInputState extends ConsumerState<ChatInput> with WidgetsBindingObserv
   void initState() {
     super.initState();
     WidgetsBinding.instance.addObserver(this);
-    _loadDraftMessage();
+    WidgetsBinding.instance.addPostFrameCallback((_) {
```
Comment (Quwaysim) [inline lib/ui/chat/widgets/chat_input.dart]: _loadDraftMessage() can go inside the addPostFrameCallback in ln 51

File: lib/ui/settings/general_settings_screen.dart [hunk 2]
```diff
@@ -134,8 +136,20 @@ class _GeneralSettingsScreenState extends ConsumerState<GeneralSettingsScreen> {
...
+      final activeAccount = activeAccountState.account;
+      if (activeAccount != null) {
+        final accountHexPubkey = PubkeyFormatter(pubkey: activeAccount.pubkey).toHex();
+        if (accountHexPubkey != null && accountHexPubkey.isNotEmpty) {
+          await DraftMessageService().clearDraftsForAccount(accountId: accountHexPubkey);
+        }
+      }
+    } catch (e) {
+      // If we can't get the active account, skip clearing drafts
+      debugPrint('Failed to clear drafts before logout: $e');
```
Comment (Quwaysim) [inline lib/ui/settings/general_settings_screen.dart]: This will show in the console even in release mode. Let's use the logger.

File: lib/ui/chat/widgets/message_widget.dart [hunk 3]
```diff
@@ -184,13 +218,38 @@ class MessageWidget extends StatelessWidget {
...
+                child: textWidget,
+              ),
+              SizedBox(width: minPadding),
+              TimeAndStatus(message: message, context: context),
+            ],
+          ),
+        );
+      }
+      // No media, use IntrinsicWidth for normal hugging behavior
+      return IntrinsicWidth(
```
Comment (Quwaysim) [inline lib/ui/chat/widgets/message_widget.dart]: From this widget's docs: This class is relatively expensive. Avoid using it where possible.


Please reconsider this approach if  possible.

File: lib/ui/settings/general_settings_screen.dart (hunk 2 above)
Comment (untreu2) [reply lib/ui/settings/general_settings_screen.dart]: You're right. Fixed.
