### PR TITLE
Fix QR login UI

### LINKED ISSUE #576: Login Scan QR visual improvements
- Chevron button looks too big, it should be 32px button with 24px chevron icon inside.
- Camera frame doesn't match the design that is used across the app - it should not have round corners, and it should have black outline.
- Bottom margin it to tight, it should be 54px.

### PR DESCRIPTION
**Pull request by untreu2**
## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore
- [ ] 🧪 Tests

## Checklist

- [x] Run `just precommit` to ensure that formatting and linting are correct
- [ ] Run `just check-flutter-coverage` to ensure that flutter coverage rules are passing
- [ ] Updated the `CHANGELOG.md` file with your changes (if they affect the user experience)

Fixes #576 

## Summary by CodeRabbit

* **New Features**
  * QR scanner is now a dedicated full-screen route — launching it navigates to a scanner screen and returns the scanned value to the previous screen.

* **Style**
  * Scanner UI redesigned to a full-page layout with a custom header and a centered, bordered 288×288 scanning card; updated padding, typography, colors, and fallback visuals.

* **Routing**
  * Added a /qr-scanner route and updated login flow to navigate to the scanner screen to receive scan results.

* **Accessibility**
  * Back button icon visually reduced but given extra padding and a larger hit target for easier tapping.

### CODE REVIEW

**Comment by untreu2** [comment]
Yes, I see that it has changed. Let me fix.

File: lib/ui/auth_flow/qr_scanner_bottom_sheet.dart [hunk 1]
```diff
@@ -1,37 +1,40 @@
...
 import 'package:whitenoise/ui/core/themes/assets.dart';
 import 'package:whitenoise/ui/core/themes/src/extensions.dart';
-import 'package:whitenoise/ui/core/ui/wn_bottom_sheet.dart';
 import 'package:whitenoise/ui/core/ui/wn_image.dart';
 import 'package:whitenoise/utils/localization_extensions.dart';
 
 class QRScannerBottomSheet extends StatefulWidget {
   const QRScannerBottomSheet({super.key});
 
   static Future<String?> show(BuildContext context) {
```
Comment (Quwaysim) [inline lib/ui/auth_flow/qr_scanner_bottom_sheet.dart]: This too. I think this shouldn't be "show()" anymore.

File: lib/ui/auth_flow/qr_scanner_bottom_sheet.dart [hunk 2]
```diff
@@ -44,65 +47,138 @@ class _QRScannerBottomSheetState extends State<QRScannerBottomSheet> {
...
+                          constraints: BoxConstraints(
+                            minHeight: constraints.maxHeight,
+                          ),
+                          child: Column(
+                            crossAxisAlignment: CrossAxisAlignment.stretch,
+                            children: [
+                              const Spacer(),
+                              Center(
+                                child: Container(
+                                  width: 288,
```
Comment (Quwaysim) [inline lib/ui/auth_flow/qr_scanner_bottom_sheet.dart]: Could we make both of these .w please? It looks small on 17 pro max sim.
